alter table "public"."products" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."products" alter column "id" add generated by default as identity;

alter table "public"."products" disable row level security;


